Cargo.toml
README.md
examples/change_animation.rs
examples/readme.rs
src/animation.rs
src/lib.rs
src/state.rs
src/warnings.rs
tests/spec.rs

The `SpriteSheetAnimation` is now an asset. Which means, one has to insert a `Handle<SpriteSheetAnimation>` created via `Assets::<SpriteSheetAnimation>::add` instead of using the `SpriteSheetAnimation` directly as a component. See the examples for more details.
* Now the animation can be created once and reused many times. Even with some different sprite-sheets, as long as they share the same frame indices, durations and animation mode (once or repeat). 
* It is now easier to check what is the current animation as the `Handle` is a unique identifier of the animation.
* Current animation is now easier (and cheaper) to change, as we no longer need to create a new animation each time. (look at the `change_animation` for an examble)
It also opens the door for storing animations ar `ron` (or …

feat!: The SpriteSheetAnimation is now an asset

---

src/state.rs

If we do not set `self.current_frame = 0;` when a `Once` animation has finished, then the animation is never able to be executed again.
With this update, the animation is able to be properly restarted next time the `Play` component is added to the corresponding entity.

Fix bug related to once animations

---

src/lib.rs
src/state.rs

Resolve #6 
This makes public the `SpriteSheetAnimationState` component which is automatically inserted on entities with a `Handle<SpriteSheetAnimation>`.
And it adds a public `pub fn reset(&mut self)` method on the state, making possible to reset the animation state.

feat: Allow to reset animation

---

examples/ping_pong.rs
src/animation.rs
src/state.rs
tests/spec.rs

Allows the creation of animations using the PingPong mode. This is a WIP solution, there may be alternative implementations.
A possible implementation would be to insert state into the PingPong mode, so that users of the Repeat and Once AnimationMode's would not pay in storage for the PingPong logic.
The problem with this approach is that users would either:
- See the internal logic inside the PingPong mode
- Not be able to construct PingPong directly (AnimationMode fields are made private to improve API).
Closes #11

feat: create ping pong animation mode

---

Cargo.toml
benches/play_component.rs
deny.toml
src/lib.rs

Resolve #30 
Using `SparseStorage` instead of the default `TableStorage` for the play component brings a clear performance improvement (around 50% faster on my laptop) for insertion/removal of the component, with undetectable impact on regular frame update.
Thanks @chrisburnor for the suggestion!

perf: faster insertion/removal of the `Play` component by using `SparseStorage`

---

src/animation.rs
src/lib.rs
src/state.rs

Adds `AnimationMode::RepeatFrom(index)` which repeats from a given index rather than going all the way back to zero. This super handy for simple animations like e.g. a torch being lit then staying lit, or a missile lighting up its motor and then looping.    
Because `AnimationMode` is `non_exhaustive` I believe this is not a breaking change.
I considered getting rid of `AnimiationMode::Repeat` and using `Animation::RepeatFrom(0)` in `fn repeat(self)`, but we can't do this without a breaking change.
I was wondering, why even expose the `AnimationMode` enum? It looks to me like it's not actually returned or taken as argument by any APIs. Could it be private to the crate? It would make it easier to make changes like this, which generalise an existing animation mode without it being a …

feat: add repeat-from animation mode

---

.github/workflows/build.yml
src/state.rs

Clippy wasn't running on the test code, so I added `--all-targets` to the github action, and fixed some missing semicolons it caught.
Based on #40 to avoid conflicts with myself; happy to drop the commit from this one if you'd rather.

chore: run clippy on all target (incl. tests)

---

src/state.rs

This prevents slow motion animations if you play at lower frame rate, without having to create special animations with less frames for lower frame rates.

feat: skip frames when delta time is greater than frame duration

---

.github/workflows/build.yml
.gitpod.yml
Cargo.toml
README.md
src/animation.rs
src/animation/parse.rs

part of #50 
Note that, this is behind an `unstable-*` feature flag, and breaking changes to the file format are to be expected until stabilization.
Also, note that this PR only adds the logic of parsing the file content. An asset loader for bevy will be added in a follow-up PR.

feat: parse animation from yaml

---

.github/workflows/build.yml
Cargo.toml
README.md
src/lib.rs
src/state.rs
tests/bevy_spec.rs

This change makes the integration with `bevy_app` optional and disabled by default.
The bevy plugin implementation is available only if this optional dependency is enabled.
To enable this integration (and make the bevy plugin available) one must enable the `bevy-app-07` feature flag.
This marks the beginning of the development of the next major version of benimator (version 4.0.0), for which I will try to make all bevy dependencies entirely optional so that I untie benimator's API stability from bevy's.
See the [related decision](https://github.com/jcornaz/benimator/blob/main/doc/adr/0002-optional-bevy-dependency.md) for more information.

feat!: make the integration with `bevy_app` optional and disabled by default

---

.github/workflows/build.yml
Cargo.toml
src/lib.rs
src/state.rs

Follow up on #73 and the [decision of making bevy dependencies optional](https://github.com/jcornaz/benimator/blob/alpha/doc/adr/0002-optional-bevy-dependency.md).

feat!: make bevy-sprite dependency optional

---

Cargo.toml
src/animation/mod.rs
src/integration/bevy_07.rs
src/lib.rs

The dependency `bevy_reflect` is now optional (behind the `bevy-07` feature).
I also removed the implementation of `Reflect` for the components that has been added eagerly without explicit need. And I am especially not enthusiast to implement `Reflect` without a very compelling reason, due to how many technical details are leaked by such implementation (which prevents changing the implementation without breaking API)
If you miss the `Reflect` implementation on benimator's components, you may open an issue. Please describe which component you'd need to implement `Reflect` and why.

refactor: make `bevy_reflect` optional (behind `bevy-07` feature)

---

src/integration/bevy_07.rs
src/state.rs

This simplifies the contract for `SpriteSheetAnimationState::update` function by no longer modifying the sprite in-place. It now only update the state. One can get the sprite index from the `sprite_frame_index` getter instead.
That function is now public too.
The state is no longer automatically reset after the last frame of a `run_once` animation. So one must explicitly reset the state if they desire to restart the animation later.

feat!: simplify state update and make it public

---

Cargo.toml
src/integration/bevy_07.rs
src/lib.rs
src/state.rs

Final step for  having the bevy dependencies completely optional (see [the related decision](https://github.com/jcornaz/benimator/blob/main/doc/adr/0002-optional-bevy-dependency.md))

refactor: make `bevy_ecs` and `bevy_core` deps optional

---

src/integration/bevy_07.rs
src/state.rs

The state now remembers what is the sprite frame index, so there is no need to pass the animation reference anymore to get it.
This notably rules out the edge-case of using a different animation to update and to get the sprite index.

refactor!: no longer require animation to get the sprite index

---

.github/workflows/build.yml
Cargo.toml
README.md
src/animation/dto.rs
src/animation/load.rs
src/animation/mod.rs
src/integration/bevy_07.rs
src/lib.rs

Resolve #62 
The feature flag `unstable-load-from-file` is removed. only `ron` or `yaml` is necessary to enable load-from file.
This change also enables the use of `serde` alone deserialization without using the loader.

feat: stabilize load-from-file

---

examples/bevy.rs
src/animation/dto.rs
src/animation/mod.rs
src/lib.rs
src/state.rs

Now `Animation::from_iter` and `Animation::from_range` take a `FrameRate` instead of a duration.
The `FrameRate` can be created from a *frame duration* or a from a *fps* (frame-per-second).

feat!: Allow to define the frame rate from FPS

---

examples/bevy.rs
src/animation/dto.rs
src/animation/mod.rs
src/lib.rs
src/state.rs

`Animation::from_range` and `Animation::from_iter` were synonyms. They are both renamed to `Animation::from_indices`.
It also add more examples describing the multiple ways to define the indices:
```rust
Animation::from_indices(0..=5, FrameRate::from_fps(12.0));
Animation::from_indices([1, 2, 3, 4], FrameRate::from_fps(12.0));
Animation::from_indices((0..5).rev(), FrameRate::from_fps(12.0));
Animation::from_indices((0..3).chain(10..15), FrameRate::from_fps(12.0));
```

feat!: Rename `from_range` and `from_iter` to `from_indices`

---

src/state.rs

Mostly to enable embedding `State` inside larger types that can then have other useful traits derived for them (e.g. `Builder` from `derive_builder` crate) which transitively require `Clone`.

feat: derive `Clone` for `State`

---

Cargo.toml
src/animation/dto.rs

The [`toml`](https://docs.rs/toml/latest/toml/#) use signed integer for number but `FrameDto` use only `visit_u64`.
- Add `visit_i64`.

fix: deserialization error when using the toml crate
